### ISSUE TITLE
您好，npm start 报错

### ISSUE THREAD

**Issue by wizali** [wssgcg1213/koa2-react-server-side-render-boilerplate#130]
```
> koa2-react-isomorphic-boilerplate@0.2.2 start /home/wizali/work/koa2-react-isomorphic-boilerplate
> node bin/development.js

Waiting for webpacking ...
util.js:1022

Error: watch /home/wizali/work/koa2-react-isomorphic-boilerplate/app ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at createFsWatchInstance (/home/wizali/work/koa2-react-isomorphic-boilerplate/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/wizali/work/koa2-react-isomorphic-boilerplate/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/wizali/work/koa2-react-isomorphic-boilerplate/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/wizali/work/koa2-react-isomorphic-boilerplate/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/wizali/work/koa2-react-isomorphic-boilerplate/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/wizali/work/koa2-react-isomorphic-boilerplate/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:123:15)

npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! koa2-react-isomorphic-boilerplate@0.2.2 start: `node bin/development.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the koa2-react-isomorphic-boilerplate@0.2.2 start script 'node bin/development.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the koa2-react-isomorphic-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/development.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs koa2-react-isomorphic-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls koa2-react-isomorphic-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/wizali/work/koa2-react-isomorphic-boilerplate/npm-debug.log
```

**Comment by wssgcg1213** [comment]
It looks like is related to the number of files you are watching. See 
http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

**Comment by wssgcg1213** [comment]
你是不是在app和platform目录下面创建了很多文件导致的？

我这边暂时没法复现这个情况，你先按照上面的调整 linux 的参数试试
